### ISSUE TITLE
[Recommendation] PurgeCSS

### ISSUE THREAD

**Issue by zaydek** [mgambill/heroicons-viewer-vue#1]
Hey there!

Are you doing anything to purge unneeded CSS classes? I noticed the load time was a little long. Let me know if you need help with this.

**Comment by mgambill** [comment]
@codex-zaydek Thanks for the suggestion, I've updated please review.

**Comment by zaydek** [comment]
Looks great! Congratulations! I’ll close this for now and open other issues as they come up if you don’t mind. 😀
