### ISSUE TITLE
[Recommendation] Dynamic sizing

### ISSUE THREAD

**Issue by zaydek** [mgambill/heroicons-viewer-vue#2]
One of the features I **love** about http://feathericons.com is the dynamic resizing utilities on the right-hand side — specifically the ability to resize icons up and down.

Are you comfortable implementing this or something like this?

**Comment by mgambill** [comment]
Would we scale by tailwind spacing defaults or just a 4px numeric scale ?

**Comment by mgambill** [comment]
Done
